Models/DeskCounter.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace HubnyxQMS.Models
{
    public class DeskCounter
    {
        public string Id { get; set; }
        public string CounterNumber { get; set; }
        public bool Status { get; set; }
        [AllowNull]
        public QMSUser QMSUser { get; set; }
        [AllowNull]
        public string QMSUserId { get; set; }
    }
}

Controllers/DeskCountersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HubnyxQMS.Data;
using HubnyxQMS.Models;
using Microsoft.AspNetCore.Authorization;

namespace HubnyxQMS.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class DeskCountersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DeskCountersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DeskCounters
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.DeskCounters.Include(d => d.QMSUser);
            return View(await applicationDbContext.OrderBy(d => d.CounterNumber).ToListAsync());
        }

        // GET: DeskCounters/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deskCounter = await _context.DeskCounters
                .Include(d => d.QMSUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deskCounter == null)
            {
                return NotFound();
            }

            return View(deskCounter);
        }

        // GET: DeskCounters/Create
        public IActionResult Create()
        {
            ViewData["QMSUserId"] = new SelectList(_context.QMSUsers.Where(c => c.Email != "admin@nyatiqms.com"), "Id", "FullName");
            return View();
        }

        // POST: DeskCounters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CounterNumber,Status,QMSUserId")] DeskCounter deskCounter)
        {
            if (ModelState.IsValid)
            {
                Guid gg = Guid.NewGuid();
                var getuniqidd = gg;
                deskCounter.Id = getuniqidd.ToString();
                deskCounter.Status = true;
                _context.Add(deskCounter);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewData["QMSUserId"] = new SelectList(_context.QMSUsers, "Id", "Id", deskCounter.QMSUserId);
            return View(deskCounter);
        }

        // GET: DeskCounters/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deskCounter = await _context.DeskCounters.FindAsync(id);
            if (deskCounter == null)
            {
                return NotFound();
            }
            ViewData["QMSUserId"] = new SelectList(_context.QMSUsers.Where(c => c.Email != "admin@nyatiqms.com"), "Id", "FullName", deskCounter.QMSUserId);
            return View(deskCounter);
        }

        // POST: DeskCounters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,CounterNumber,Status,QMSUserId")] DeskCounter deskCounter)
        {
            if (id != deskCounter.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                try
                {
                    deskCounter.Status = true;
                    _context.Update(deskCounter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeskCounterExists(deskCounter.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["QMSUserId"] = new SelectList(_context.QMSUsers, "Id", "Id", deskCounter.QMSUserId);
            return View(deskCounter);
        }

        // GET: DeskCounters/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deskCounter = await _context.DeskCounters
                .Include(d => d.QMSUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deskCounter == null)
            {
                return NotFound();
            }

            return View(deskCounter);
        }

        // POST: DeskCounters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var deskCounter = await _context.DeskCounters.FindAsync(id);
            _context.DeskCounters.Remove(deskCounter);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeskCounterExists(string id)
        {
            return _context.DeskCounters.Any(e => e.Id == id);
        }
    }
}

Views/DeskCounters/Create.cshtml
@model HubnyxQMS.Models.DeskCounter

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-4">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Add Counter</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->
                <!-- Page-body start -->
                <div class="page-body">
                    <form asp-action="Create">
                        <div class="auth-box card">
                            <div class="auth-box card">
                                <div class="card-block">
                                    <div class="row m-b-20">
                                        <div class="col-md-12">
                                            <h3 class="text-center">
                                                Nyati Sacco QMS | Counters
                                                <a asp-action="Index" asp-controller="DeskCounters" class="btn btn-danger btn-sm float-right">Back</a>
                                            </h3>

                                        </div>
                                    </div>
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group form-primary">
                                        <label for="exampleFormControlSelect1">Counter Number</label>
                                        <input asp-for="CounterNumber" class="form-control" required="" placeholder="Name">
                                        <span asp-validation-for="CounterNumber" class="form-bar"></span>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Agent</label>
                                        <select asp-for="QMSUserId" class="form-control" asp-items="ViewBag.QMSUserId"></select>
                                    </div>
                                    <div class="row m-t-30">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-success btn-md btn-block waves-effect waves-light text-center m-b-20">Create</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Page-body end -->
    </div>
</div>

@*<h1>Create</h1>

<h4>DeskCounter</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CounterNumber" class="control-label"></label>
                <input asp-for="CounterNumber" class="form-control" />
                <span asp-validation-for="CounterNumber" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="QMSUserId" class="control-label"></label>
                <select asp-for="QMSUserId" class ="form-control" asp-items="ViewBag.QMSUserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>*@

Views/DeskCounters/Delete.cshtml
@model HubnyxQMS.Models.DeskCounter

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeskCounter</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CounterNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CounterNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QMSUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QMSUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/DeskCounters/Details.cshtml
@model HubnyxQMS.Models.DeskCounter

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>DeskCounter</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CounterNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CounterNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QMSUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QMSUser.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/DeskCounters/Edit.cshtml
@model HubnyxQMS.Models.DeskCounter

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-4">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Add Counter</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->
                <!-- Page-body start -->
                <div class="page-body">
                    <form asp-action="Edit">
                        <input type="hidden" asp-for="Id" />
                        <div class="auth-box card">
                            <div class="auth-box card">
                                <div class="card-block">
                                    <div class="row m-b-20">
                                        <div class="col-md-12">
                                            <h3 class="text-center">
                                                Nyati Sacco QMS | Counters
                                                <a asp-action="Index" asp-controller="DeskCounters" class="btn btn-danger btn-sm float-right">Back</a>
                                            </h3>

                                        </div>
                                    </div>
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group form-primary">
                                        <label for="exampleFormControlSelect1">Counter Number</label>
                                        <input asp-for="CounterNumber" class="form-control" required="" placeholder="Name">
                                        <span asp-validation-for="CounterNumber" class="form-bar"></span>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Agent</label>
                                        <select asp-for="QMSUserId" class="form-control" asp-items="ViewBag.QMSUserId"></select>
                                    </div>
                                    <div class="row m-t-30">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-success btn-md btn-block waves-effect waves-light text-center m-b-20">ReAssign</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Page-body end -->
    </div>
</div>

Views/DeskCounters/Index.cshtml
@model IEnumerable<HubnyxQMS.Models.DeskCounter>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-4">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>All Counters</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->
                <!-- Page-body start -->
                <div class="page-body">

                    <div class="card">
                        <div class="card-header">
                            <a asp-action="Create" class="btn btn-success btn-sm">Create</a>
                        </div>
                        <div class="card-block table-border-style">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Number</th>
                                            <th>Status</th>
                                            <th>Agent</th>
                                            <th>Assign</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                        <tr>
                                            <td>
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CounterNumber)
                                            </td>
                                            @if (item.Status == true)
                                            {
                                                <td>
                                                    <a href="#" class="btn btn-success btn-sm">Active</a>
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    <a href="#" class="btn btn-danger btn-sm">Non-Active</a>
                                                </td>
                                            }
                                            <td>
                                                @Html.DisplayFor(modelItem => item.QMSUser.FullName)
                                            </td>
                                            <td>
                                                <a asp-action="Edit" class="btn btn-dark btn-sm" asp-route-id="@item.Id">ReAssign</a>
                                            </td>
                                        </tr>
                                        }


                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page-body end -->
    </div>
</div>

@*<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CounterNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QMSUser)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CounterNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QMSUser.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@